"""empty message

Revision ID: 7d447ca5713b
Revises: eb6c73198961
Create Date: 2025-11-17 13:25:06.085730

"""
from alembic import op
import sqlalchemy as sa
# import app.models

# revision identifiers, used by Alembic.
revision = '7d447ca5713b'
down_revision = 'eb6c73198961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=app.models.GUID(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=app.models.GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
