"""empty message

Revision ID: c8acec76edab
Revises: 
Create Date: 2025-11-30 17:46:03.069977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8acec76edab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitee_img', sa.String(length=255), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('invitee', schema=None) as batch_op:
        batch_op.drop_column('invitee_img')

    # ### end Alembic commands ###
